kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "journalist.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "journalist.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: httpserver
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "journalist.chart" . }}
  annotations:
    kubernetes.io/change-cause: "{{ .Values.journalist.changecause }}"
spec:
  replicas: {{ .Values.journalist.replicas }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "journalist.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "journalist.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        kubernetes.io/change-cause: "{{ .Values.journalist.changecause }}"
    spec:
      imagePullSecrets:
        - name: giosg.hub.docker.com
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.journalist.image.repository }}:{{ .Values.journalist.image.tag }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
          resources:
            limits:
              memory: "1Gi"
              cpu: "2.0"
            requests:
              memory: "500Mi"
              cpu: "1.0"
          livenessProbe:
            httpGet:
              path: /
              port: http