kind: Service
apiVersion: v1
metadata:
  name: {{ include "journalist.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "journalist.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "journalist.chart" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "journalist.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http